# Generated by Django 5.0.7 on 2025-09-21 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_paid_at_order_payment_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_provider',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payriff_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payriff_transaction_id',
        ),
    ]
