# Generated by Django 5.0.7 on 2025-09-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('story', models.TextField(blank=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('product_models', models.IntegerField(default=0)),
                ('happy_customers', models.IntegerField(default=0)),
                ('quality_rating', models.CharField(blank=True, max_length=50)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('values', models.JSONField(blank=True, default=list)),
                ('team', models.JSONField(blank=True, default=list)),
                ('technology_title', models.CharField(blank=True, max_length=255)),
                ('technology_text', models.TextField(blank=True)),
                ('technology_features', models.JSONField(blank=True, default=list)),
                ('technology_stats', models.JSONField(blank=True, default=list)),
                ('contact_title', models.CharField(blank=True, max_length=255)),
                ('contact_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('email_primary', models.EmailField(blank=True, max_length=254)),
                ('email_secondary', models.EmailField(blank=True, max_length=254)),
                ('phone_primary', models.CharField(blank=True, max_length=50)),
                ('phone_secondary', models.CharField(blank=True, max_length=50)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('working_hours', models.JSONField(blank=True, default=list)),
                ('form_title', models.CharField(blank=True, max_length=255)),
                ('form_text', models.TextField(blank=True)),
                ('support_title', models.CharField(blank=True, max_length=255)),
                ('support_text', models.TextField(blank=True)),
                ('support_phone', models.CharField(blank=True, max_length=50)),
                ('catalog_title', models.CharField(blank=True, max_length=255)),
                ('catalog_text', models.TextField(blank=True)),
                ('catalog_link', models.URLField(blank=True)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('map_section_title', models.CharField(blank=True, max_length=255)),
                ('map_heading', models.CharField(blank=True, max_length=255)),
                ('map_address', models.CharField(blank=True, max_length=255)),
                ('map_button_text', models.CharField(blank=True, max_length=255)),
                ('map_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('terms_pdf', models.FileField(blank=True, null=True, upload_to='legal/')),
                ('privacy_pdf', models.FileField(blank=True, null=True, upload_to='legal/')),
                ('footer_description', models.TextField(blank=True)),
                ('footer_email', models.EmailField(blank=True, max_length=254)),
                ('footer_phone', models.CharField(blank=True, max_length=64)),
                ('footer_bottom_text', models.TextField(blank=True)),
            ],
        ),
    ]
