# Generated by Django 5.0.7 on 2025-09-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
